services:
  postgres:
    image: postgres:16
    restart: always
    expose:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./database:/var/lib/postgresql/data:Z
    networks: ["events_network"]
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMINS=${ADMINS}
      - DATABASE_URL=${DATABASE_URL}
    networks: ["events_network"]
networks:
  events_network: {}
